base_url = "https://toniogela.dev"
default_language = "en"
compile_sass = true
build_search_index = false

[languages.en]
title = "TonioGela's"
description = "\"In order to understand recursion, one must first understand recursion\""
generate_feed = false
feed_limit = 1000

[languages.it]
title = "TonioGela's"
description = "\"In order to understand recursion, one must first understand recursion\""
generate_feed = true
feed_limit = 1000

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes"]
highlight_theme = "base16-ocean-dark"
render_emoji = true

[extra]
profile = "avatar.jpg"
author = "Antonio Gelameris"
google_analytics_id = "G-JJW5KRXYVV"

[[extra.socials]]
icon = "github"
uri = "https://github.com/TonioGela"

[[extra.socials]]
icon = "mastodon"
uri = "https://hachyderm.io/@toniogela"


[[extra.socials]]
icon = "terminal"
display = "about me"
uri = "/about"
blank = false

[[extra.socials]]
icon = "twitter"
uri = "https://twitter.com/toniogela"


[[extra.socials]]
icon = "linkedin"
uri = "https://www.linkedin.com/in/toniogela/"

[extra.comments] # Optional
repo = "TonioGela/toniogela.dev-comments"
theme = "github-dark"
term = "url"

[extra.font_awesome]
kit = "e307e34624"
