base_url = "https://toniogela.dev"
title = "TonioGela's"
description="\"In order to understand recursion, one must first understand recursion\""
default_language = "en"
languages = [
    {code = "it", feed = true}
]

generate_feed = true
feed_limit = 1000
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "nord"
render_emoji = true

[extra]
profile = "avatar.jpg" # the name of the profile picture in static/

[[extra.socials]]
icon = "twitter"
uri = "https://twitter.com/toniogela"

[[extra.socials]]
icon = "github"
uri = "https://github.com/TonioGela"

[[extra.socials]]
icon = "address-card"
icon_class = "far"
display = "about me"
uri = "/about"
blank = false

[[extra.socials]]
icon = "linkedin"
uri = "https://www.linkedin.com/in/toniogela/"

[extra.comments] # Optional
repo = "TonioGela/toniogela.dev-comments"
theme = "github-dark"
term = "url"

[extra.font_awesome]
kit = "e307e34624"