let
  pins = import ./npins;
  pkgs = import pins.nixpkgs-unstable { };
  inherit (pkgs) lib;

  # Kept out of the repo on purpose: the deploy config is part of the build,
  # not something to hand-edit next to the posts.
  wrangler = pkgs.writeText "wrangler.jsonc" (
    builtins.toJSON {
      name = "blog";
      compatibility_date = "2026-09-11";
      # no "main": assets-only, so requests never start an isolate
      assets = {
        directory = "./public";
        not_found_handling = "404-page";
      };
      routes = [
        {
          pattern = "toniogela.dev";
          custom_domain = true;
        }
      ];
    }
  );

  # Applied by Cloudflare to every static asset response. No CSP: the site
  # loads inline styles and third-party embeds, so it would only break things.
  # No HSTS either, that is enabled zone-wide in the dashboard.
  headers = pkgs.writeText "_headers" ''
    /*
      Referrer-Policy: strict-origin-when-cross-origin
      X-Frame-Options: SAMEORIGIN
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  '';
in
pkgs.stdenvNoCC.mkDerivation {
  name = "blog";
  # only what zola reads, so README/CI edits don't rebuild the site
  src = lib.fileset.toSource {
    root = ./.;
    fileset = lib.fileset.unions [
      ./config.toml
      ./content
      ./font
      ./sass
      ./syntaxes
      ./templates
      # generated by zola, never an input
      (lib.fileset.difference ./static (lib.fileset.maybeMissing ./static/processed_images))
    ];
  };
  nativeBuildInputs = [ pkgs.zola ];
  buildPhase = "zola build --output-dir public";
  installPhase = ''
    mkdir -p $out
    cp -r public $out/public
    cp ${headers} $out/public/_headers
    cp ${wrangler} $out/wrangler.jsonc
  '';
}
