let
  pins = import ./npins;
  pkgs = import pins.nixpkgs-unstable { };
  inherit (pkgs) lib;

  # Kept out of the repo on purpose: the deploy config is part of the build,
  # not something to hand-edit next to the posts.
  wrangler = pkgs.writeText "wrangler.jsonc" (
    builtins.toJSON {
      name = "blog";
      compatibility_date = "2026-09-11";
      # no "main": assets-only, so requests never start an isolate
      assets = {
        directory = "./public";
        not_found_handling = "404-page";
      };
      routes = [
        {
          pattern = "toniogela.dev";
          custom_domain = true;
        }
      ];
    }
  );

  # Applied by Cloudflare to every static asset response. HSTS is not here:
  # the zone-level setting already sends it, on redirects too.
  #
  # CSP: giscus is the only third party the pages load; youtube/vimeo are there
  # for the embed shortcodes, unused today but one post away from breaking.
  # style-src allows inline for the same reason: the image shortcodes emit
  # style attributes. The one inline script zola emits (the /page/1 redirect)
  # falls back to its own <noscript> meta refresh, so it needs no exception.
  headers = pkgs.writeText "_headers" ''
    /*
      Content-Security-Policy: default-src 'self'; script-src 'self' https://giscus.app; style-src 'self' 'unsafe-inline' https://giscus.app; img-src 'self' data:; font-src 'self'; connect-src 'self' https://giscus.app; frame-src https://giscus.app https://www.youtube.com https://player.vimeo.com; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'self'
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      X-Frame-Options: SAMEORIGIN
      Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  '';
in
pkgs.stdenvNoCC.mkDerivation {
  name = "blog";
  # only what zola reads, so README/CI edits don't rebuild the site
  src = lib.fileset.toSource {
    root = ./.;
    fileset = lib.fileset.unions [
      ./config.toml
      ./content
      ./font
      ./sass
      ./syntaxes
      ./templates
      # generated by zola, never an input
      (lib.fileset.difference ./static (lib.fileset.maybeMissing ./static/processed_images))
    ];
  };
  nativeBuildInputs = [ pkgs.zola ];
  buildPhase = "zola build --output-dir public";
  installPhase = ''
    mkdir -p $out
    cp -r public $out/public
    cp ${headers} $out/public/_headers
    cp ${wrangler} $out/wrangler.jsonc
  '';
}
