[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

[context.production]
  command = "zola build --base-url https://toniogela.dev"

[context.drafts]
  command = "zola build --drafts --base-url https://drafts--toniogela.netlify.app"