base_url = "https://blog.toniogela.dev"
title = "TonioGela's"
description="\"In order to understand recursion, one must first understand recursion\""
default_language = "en"

generate_feed = true
feed_limit = 1000
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
profile = "avatar.jpg" # the name of the profile picture in static/
color_themes = ["dark"]
country_flags = true # Display languages as country flags. Defaults to false. I never used it.

[[extra.socials]]
icon = "twitter"
uri = "https://twitter.com/toniogela"

[[extra.socials]]
icon = "github"
uri = "https://github.com/TonioGela"

[[extra.socials]]
icon = "address-card"
icon_class = "far"
display = "about me"
uri = "/about"
blank = false

[[extra.socials]]
icon = "linkedin"
uri = "https://www.linkedin.com/in/toniogela/"

[extra.comments] # Optional
repo = "insipx/Ergo"
theme = "github-dark"
label = "comment" # Optional
#issue_number = 1 # Specify either this or term
term = "pathname"

[extra.font_awesome]
kit = "e307e34624"