on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          CHECK_LINKS: true
          CHECK_FLAGS: --drafts
          BUILD_THEMES: false
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
